FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04
LABEL maintainer "Gemfield <gemfield@civilnet.cn>"
ARG PYTHON_VERSION=3.8

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y --no-install-recommends build-essential \
    vim wget curl bzip2 git unzip g++ binutils cmake locales \
    ca-certificates apt-transport-https gnupg software-properties-common \
    libjpeg-dev libpng-dev iputils-ping net-tools libgl1 libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && dpkg-reconfigure -f noninteractive tzdata && locale-gen zh_CN.utf8

ENV LC_ALL zh_CN.UTF-8
ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN.UTF-8

#conda
RUN curl -o ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda install -y python=$PYTHON_VERSION numpy pyyaml scipy ipython mkl mkl-include cffi ninja setuptools typing_extensions future six requests dataclasses cython typing && \
     /opt/conda/bin/conda install -c pytorch magma-cuda111 &&  \
     /opt/conda/bin/pip3 install --no-cache-dir Pillow opencv-python confluent_kafka easydict sklearn matplotlib tensorboard fonttools onnx-coreml coremltools && \
     /opt/conda/bin/conda clean -ya
ENV PATH /opt/conda/bin:$PATH

WORKDIR /gemfield
