#Ubuntu 18.04
FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel
LABEL maintainer "Gemfield <gemfield@civilnet.cn>"
#wa for Clearsigned file isn't valid, got 'NOSPLIT'
RUN mv /etc/apt/sources.list.d/cuda.list /etc/apt/sources.list.d/cuda.list.bk && mv /etc/apt/sources.list.d/nvidia-ml.list /etc/apt/sources.list.d/nvidia-ml.list.bk
RUN apt-get update && apt-get install -y --no-install-recommends \
        vim locales libglib2.0-0 libsm6 libxrender1 libxext6 net-tools iputils-ping git g++ swig \
        python-pybind11 wget apt-transport-https ca-certificates gnupg software-properties-common \
        libopenblas-dev libgl1-mesa-glx curl

#for latest cmake version, and for Faiss build.
RUN wget -qO - https://apt.kitware.com/keys/kitware-archive-latest.asc |  apt-key add -
RUN apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' && \
    apt-get update && apt-get install -y --no-install-recommends cmake

#python3
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple numpy opencv_python confluent_kafka easydict bcolz sklearn matplotlib tensorboard
RUN pip install --no-cache-dir deepvac

WORKDIR /gemfield

RUN locale-gen zh_CN.utf8
ENV TZ=Asia/Shanghai
ENV LANG=zh_CN.utf8

#####


RUN curl -fsSL -v -o ~/miniconda.sh -O  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda install -y python=${PYTHON_VERSION} conda-build pyyaml numpy ipython&& \
    /opt/conda/bin/conda clean -ya

export PATH=/opt/conda/bin:$PATH

RUN conda install -y pytorch torchvision cudatoolkit=10.2 -c pytorch