FROM gemfield/cuda:11.1.1-cudnn8-devel-ubuntu20.04
LABEL maintainer "Gemfield <gemfield@civilnet.cn>"
TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX"

WORKDIR /opt/pytorch
COPY . .

RUN git submodule sync && git submodule update --init --recursive

RUN TORCH_CUDA_ARCH_LIST=$TORCH_CUDA_ARCH_LIST TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
    CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" \
    pip install -v .

WORKDIR /gemfield