FROM gemfield/conda-cuda-base as base

FROM base as patchelf
RUN git clone https://github.com/NixOS/patchelf && cd patchelf && sed -i 's/serial/parallel/g' configure.ac && \
    ./bootstrap.sh && ./configure && make && make install && cd .. && rm -rf patchelf && cp $(which patchelf) /patchelf

FROM base as conda
# Install Anaconda
RUN wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    chmod +x  Miniconda3-latest-Linux-x86_64.sh && \
    ./Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm Miniconda3-latest-Linux-x86_64.sh && export PATH=/opt/conda/bin:$PATH && \
    conda install -y conda-build anaconda-client ninja && \
    conda remove -y --force patchelf && rm install_conda.sh && \
    /opt/conda/bin/conda install -y conda-package-handling=1.6.0

# conda-package-handling fails out for larger tarballs,
# see: https://github.com/conda/conda-package-handling/issues/71

FROM base as final
COPY --from=patchelf /patchelf            /usr/local/bin/patchelf
COPY --from=conda    /opt/conda           /opt/conda
ADD ./jni.h     /usr/local/include/jni.h
ENV PATH /opt/conda/bin:$PATH
RUN chmod o+rw /usr/local
RUN touch /.condarc && \
    chmod o+rw /.condarc && \
    chmod -R o+rw /opt/conda
